# pytest_unittest
unittest mock function, pytest fixture, overflow error + raises

E' stato utilizzato il mock di unittest per simulare la chiamata ad un database con esito fasullo
E' stata utilizzata una fixture per implementare una routine all'interno del test
E' stato utilizzato un overflow error in combinazione con raises, in modo che il fallimento di una funzione = test passato
